FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app
COPY ./ ./
WORKDIR /app/helper-module
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/helper-module/out .
RUN rm -f /app/appsettings.json
ENTRYPOINT ["dotnet","helper-module.dll"]